// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unnecessary_cast, override_on_non_overriding_member
// ignore_for_file: strict_raw_type, inference_failure_on_untyped_parameter

part of 'user.model.dart';

class UserModelMapper extends ClassMapperBase<UserModel> {
  UserModelMapper._();

  static UserModelMapper? _instance;
  static UserModelMapper ensureInitialized() {
    if (_instance == null) {
      MapperContainer.globals.use(_instance = UserModelMapper._());
      UserEntityMapper.ensureInitialized();
      UserTypeMapper.ensureInitialized();
      LocationEntityMapper.ensureInitialized();
      ChannelEntityMapper.ensureInitialized();
      PostEntityMapper.ensureInitialized();
      StoryEntityMapper.ensureInitialized();
      CommentEntityMapper.ensureInitialized();
      ReportEntityMapper.ensureInitialized();
      TokenModelMapper.ensureInitialized();
    }
    return _instance!;
  }

  @override
  final String id = 'UserModel';

  static String _$id(UserModel v) => v.id;
  static const Field<UserModel, String> _f$id = Field('id', _$id, key: r'_id');
  static String? _$username(UserModel v) => v.username;
  static const Field<UserModel, String> _f$username =
      Field('username', _$username);
  static String? _$email(UserModel v) => v.email;
  static const Field<UserModel, String> _f$email = Field('email', _$email);
  static bool? _$isBanned(UserModel v) => v.isBanned;
  static const Field<UserModel, bool> _f$isBanned =
      Field('isBanned', _$isBanned, key: r'is_banned');
  static bool? _$isDeleted(UserModel v) => v.isDeleted;
  static const Field<UserModel, bool> _f$isDeleted =
      Field('isDeleted', _$isDeleted, key: r'is_deleted');
  static UserType _$userType(UserModel v) => v.userType;
  static const Field<UserModel, UserType> _f$userType =
      Field('userType', _$userType, key: r'user_type');
  static bool? _$official(UserModel v) => v.official;
  static const Field<UserModel, bool> _f$official =
      Field('official', _$official);
  static int? _$distance(UserModel v) => v.distance;
  static const Field<UserModel, int> _f$distance =
      Field('distance', _$distance);
  static int? _$points(UserModel v) => v.points;
  static const Field<UserModel, int> _f$points = Field('points', _$points);
  static LocationEntity? _$location(UserModel v) => v.location;
  static const Field<UserModel, LocationEntity> _f$location =
      Field('location', _$location, opt: true);
  static String? _$provider(UserModel v) => v.provider;
  static const Field<UserModel, String> _f$provider =
      Field('provider', _$provider, opt: true);
  static DateTime? _$createdAt(UserModel v) => v.createdAt;
  static const Field<UserModel, DateTime> _f$createdAt =
      Field('createdAt', _$createdAt, key: r'created_at');
  static bool? _$autoGeneratedUsername(UserModel v) => v.autoGeneratedUsername;
  static const Field<UserModel, bool> _f$autoGeneratedUsername = Field(
      'autoGeneratedUsername', _$autoGeneratedUsername,
      key: r'auto_generated_username', opt: true);
  static int? _$usernameChangeCounter(UserModel v) => v.usernameChangeCounter;
  static const Field<UserModel, int> _f$usernameChangeCounter = Field(
      'usernameChangeCounter', _$usernameChangeCounter,
      key: r'username_change_counter', opt: true);
  static List<ChannelEntity>? _$channels(UserModel v) => v.channels;
  static const Field<UserModel, List<ChannelEntity>> _f$channels =
      Field('channels', _$channels, opt: true);
  static String? _$deviceType(UserModel v) => v.deviceType;
  static const Field<UserModel, String> _f$deviceType =
      Field('deviceType', _$deviceType, key: r'device_type', opt: true);
  static String? _$deviceId(UserModel v) => v.deviceId;
  static const Field<UserModel, String> _f$deviceId =
      Field('deviceId', _$deviceId, key: r'device_id', opt: true);
  static String? _$providerId(UserModel v) => v.providerId;
  static const Field<UserModel, String> _f$providerId =
      Field('providerId', _$providerId, key: r'provider_id', opt: true);
  static List<PostEntity>? _$posts(UserModel v) => v.posts;
  static const Field<UserModel, List<PostEntity>> _f$posts =
      Field('posts', _$posts, opt: true);
  static List<StoryEntity>? _$storys(UserModel v) => v.storys;
  static const Field<UserModel, List<StoryEntity>> _f$storys =
      Field('storys', _$storys, opt: true);
  static List<CommentEntity>? _$comments(UserModel v) => v.comments;
  static const Field<UserModel, List<CommentEntity>> _f$comments =
      Field('comments', _$comments, opt: true);
  static List<ReportEntity>? _$reports(UserModel v) => v.reports;
  static const Field<UserModel, List<ReportEntity>> _f$reports =
      Field('reports', _$reports, opt: true);
  static List<ReportEntity>? _$reporteds(UserModel v) => v.reporteds;
  static const Field<UserModel, List<ReportEntity>> _f$reporteds =
      Field('reporteds', _$reporteds, opt: true);
  static TokenModel? _$tokens(UserModel v) => v.tokens;
  static const Field<UserModel, TokenModel> _f$tokens =
      Field('tokens', _$tokens, opt: true);

  @override
  final MappableFields<UserModel> fields = const {
    #id: _f$id,
    #username: _f$username,
    #email: _f$email,
    #isBanned: _f$isBanned,
    #isDeleted: _f$isDeleted,
    #userType: _f$userType,
    #official: _f$official,
    #distance: _f$distance,
    #points: _f$points,
    #location: _f$location,
    #provider: _f$provider,
    #createdAt: _f$createdAt,
    #autoGeneratedUsername: _f$autoGeneratedUsername,
    #usernameChangeCounter: _f$usernameChangeCounter,
    #channels: _f$channels,
    #deviceType: _f$deviceType,
    #deviceId: _f$deviceId,
    #providerId: _f$providerId,
    #posts: _f$posts,
    #storys: _f$storys,
    #comments: _f$comments,
    #reports: _f$reports,
    #reporteds: _f$reporteds,
    #tokens: _f$tokens,
  };

  static UserModel _instantiate(DecodingData data) {
    return UserModel(
        id: data.dec(_f$id),
        username: data.dec(_f$username),
        email: data.dec(_f$email),
        isBanned: data.dec(_f$isBanned),
        isDeleted: data.dec(_f$isDeleted),
        userType: data.dec(_f$userType),
        official: data.dec(_f$official),
        distance: data.dec(_f$distance),
        points: data.dec(_f$points),
        location: data.dec(_f$location),
        provider: data.dec(_f$provider),
        createdAt: data.dec(_f$createdAt),
        autoGeneratedUsername: data.dec(_f$autoGeneratedUsername),
        usernameChangeCounter: data.dec(_f$usernameChangeCounter),
        channels: data.dec(_f$channels),
        deviceType: data.dec(_f$deviceType),
        deviceId: data.dec(_f$deviceId),
        providerId: data.dec(_f$providerId),
        posts: data.dec(_f$posts),
        storys: data.dec(_f$storys),
        comments: data.dec(_f$comments),
        reports: data.dec(_f$reports),
        reporteds: data.dec(_f$reporteds),
        tokens: data.dec(_f$tokens));
  }

  @override
  final Function instantiate = _instantiate;

  static UserModel fromMap(Map<String, dynamic> map) {
    return ensureInitialized().decodeMap<UserModel>(map);
  }

  static UserModel fromJson(String json) {
    return ensureInitialized().decodeJson<UserModel>(json);
  }
}

mixin UserModelMappable {
  String toJson() {
    return UserModelMapper.ensureInitialized()
        .encodeJson<UserModel>(this as UserModel);
  }

  Map<String, dynamic> toMap() {
    return UserModelMapper.ensureInitialized()
        .encodeMap<UserModel>(this as UserModel);
  }

  UserModelCopyWith<UserModel, UserModel, UserModel> get copyWith =>
      _UserModelCopyWithImpl(this as UserModel, $identity, $identity);
  @override
  String toString() {
    return UserModelMapper.ensureInitialized()
        .stringifyValue(this as UserModel);
  }

  @override
  bool operator ==(Object other) {
    return UserModelMapper.ensureInitialized()
        .equalsValue(this as UserModel, other);
  }

  @override
  int get hashCode {
    return UserModelMapper.ensureInitialized().hashValue(this as UserModel);
  }
}

extension UserModelValueCopy<$R, $Out> on ObjectCopyWith<$R, UserModel, $Out> {
  UserModelCopyWith<$R, UserModel, $Out> get $asUserModel =>
      $base.as((v, t, t2) => _UserModelCopyWithImpl(v, t, t2));
}

abstract class UserModelCopyWith<$R, $In extends UserModel, $Out>
    implements UserEntityCopyWith<$R, $In, $Out> {
  @override
  LocationEntityCopyWith<$R, LocationEntity, LocationEntity>? get location;
  @override
  ListCopyWith<$R, ChannelEntity,
      ChannelEntityCopyWith<$R, ChannelEntity, ChannelEntity>>? get channels;
  @override
  ListCopyWith<$R, PostEntity, PostEntityCopyWith<$R, PostEntity, PostEntity>>?
      get posts;
  @override
  ListCopyWith<$R, StoryEntity,
      StoryEntityCopyWith<$R, StoryEntity, StoryEntity>>? get storys;
  @override
  ListCopyWith<$R, CommentEntity,
      CommentEntityCopyWith<$R, CommentEntity, CommentEntity>>? get comments;
  @override
  ListCopyWith<$R, ReportEntity,
      ReportEntityCopyWith<$R, ReportEntity, ReportEntity>>? get reports;
  @override
  ListCopyWith<$R, ReportEntity,
      ReportEntityCopyWith<$R, ReportEntity, ReportEntity>>? get reporteds;
  TokenModelCopyWith<$R, TokenModel, TokenModel>? get tokens;
  @override
  $R call(
      {String? id,
      String? username,
      String? email,
      bool? isBanned,
      bool? isDeleted,
      UserType? userType,
      bool? official,
      int? distance,
      int? points,
      LocationEntity? location,
      String? provider,
      DateTime? createdAt,
      bool? autoGeneratedUsername,
      int? usernameChangeCounter,
      List<ChannelEntity>? channels,
      String? deviceType,
      String? deviceId,
      String? providerId,
      List<PostEntity>? posts,
      List<StoryEntity>? storys,
      List<CommentEntity>? comments,
      List<ReportEntity>? reports,
      List<ReportEntity>? reporteds,
      TokenModel? tokens});
  UserModelCopyWith<$R2, $In, $Out2> $chain<$R2, $Out2>(Then<$Out2, $R2> t);
}

class _UserModelCopyWithImpl<$R, $Out>
    extends ClassCopyWithBase<$R, UserModel, $Out>
    implements UserModelCopyWith<$R, UserModel, $Out> {
  _UserModelCopyWithImpl(super.value, super.then, super.then2);

  @override
  late final ClassMapperBase<UserModel> $mapper =
      UserModelMapper.ensureInitialized();
  @override
  LocationEntityCopyWith<$R, LocationEntity, LocationEntity>? get location =>
      $value.location?.copyWith.$chain((v) => call(location: v));
  @override
  ListCopyWith<$R, ChannelEntity,
          ChannelEntityCopyWith<$R, ChannelEntity, ChannelEntity>>?
      get channels => $value.channels != null
          ? ListCopyWith($value.channels!, (v, t) => v.copyWith.$chain(t),
              (v) => call(channels: v))
          : null;
  @override
  ListCopyWith<$R, PostEntity, PostEntityCopyWith<$R, PostEntity, PostEntity>>?
      get posts => $value.posts != null
          ? ListCopyWith($value.posts!, (v, t) => v.copyWith.$chain(t),
              (v) => call(posts: v))
          : null;
  @override
  ListCopyWith<$R, StoryEntity,
          StoryEntityCopyWith<$R, StoryEntity, StoryEntity>>?
      get storys => $value.storys != null
          ? ListCopyWith($value.storys!, (v, t) => v.copyWith.$chain(t),
              (v) => call(storys: v))
          : null;
  @override
  ListCopyWith<$R, CommentEntity,
          CommentEntityCopyWith<$R, CommentEntity, CommentEntity>>?
      get comments => $value.comments != null
          ? ListCopyWith($value.comments!, (v, t) => v.copyWith.$chain(t),
              (v) => call(comments: v))
          : null;
  @override
  ListCopyWith<$R, ReportEntity,
          ReportEntityCopyWith<$R, ReportEntity, ReportEntity>>?
      get reports => $value.reports != null
          ? ListCopyWith($value.reports!, (v, t) => v.copyWith.$chain(t),
              (v) => call(reports: v))
          : null;
  @override
  ListCopyWith<$R, ReportEntity,
          ReportEntityCopyWith<$R, ReportEntity, ReportEntity>>?
      get reporteds => $value.reporteds != null
          ? ListCopyWith($value.reporteds!, (v, t) => v.copyWith.$chain(t),
              (v) => call(reporteds: v))
          : null;
  @override
  TokenModelCopyWith<$R, TokenModel, TokenModel>? get tokens =>
      $value.tokens?.copyWith.$chain((v) => call(tokens: v));
  @override
  $R call(
          {String? id,
          Object? username = $none,
          Object? email = $none,
          Object? isBanned = $none,
          Object? isDeleted = $none,
          UserType? userType,
          Object? official = $none,
          Object? distance = $none,
          Object? points = $none,
          Object? location = $none,
          Object? provider = $none,
          Object? createdAt = $none,
          Object? autoGeneratedUsername = $none,
          Object? usernameChangeCounter = $none,
          Object? channels = $none,
          Object? deviceType = $none,
          Object? deviceId = $none,
          Object? providerId = $none,
          Object? posts = $none,
          Object? storys = $none,
          Object? comments = $none,
          Object? reports = $none,
          Object? reporteds = $none,
          Object? tokens = $none}) =>
      $apply(FieldCopyWithData({
        if (id != null) #id: id,
        if (username != $none) #username: username,
        if (email != $none) #email: email,
        if (isBanned != $none) #isBanned: isBanned,
        if (isDeleted != $none) #isDeleted: isDeleted,
        if (userType != null) #userType: userType,
        if (official != $none) #official: official,
        if (distance != $none) #distance: distance,
        if (points != $none) #points: points,
        if (location != $none) #location: location,
        if (provider != $none) #provider: provider,
        if (createdAt != $none) #createdAt: createdAt,
        if (autoGeneratedUsername != $none)
          #autoGeneratedUsername: autoGeneratedUsername,
        if (usernameChangeCounter != $none)
          #usernameChangeCounter: usernameChangeCounter,
        if (channels != $none) #channels: channels,
        if (deviceType != $none) #deviceType: deviceType,
        if (deviceId != $none) #deviceId: deviceId,
        if (providerId != $none) #providerId: providerId,
        if (posts != $none) #posts: posts,
        if (storys != $none) #storys: storys,
        if (comments != $none) #comments: comments,
        if (reports != $none) #reports: reports,
        if (reporteds != $none) #reporteds: reporteds,
        if (tokens != $none) #tokens: tokens
      }));
  @override
  UserModel $make(CopyWithData data) => UserModel(
      id: data.get(#id, or: $value.id),
      username: data.get(#username, or: $value.username),
      email: data.get(#email, or: $value.email),
      isBanned: data.get(#isBanned, or: $value.isBanned),
      isDeleted: data.get(#isDeleted, or: $value.isDeleted),
      userType: data.get(#userType, or: $value.userType),
      official: data.get(#official, or: $value.official),
      distance: data.get(#distance, or: $value.distance),
      points: data.get(#points, or: $value.points),
      location: data.get(#location, or: $value.location),
      provider: data.get(#provider, or: $value.provider),
      createdAt: data.get(#createdAt, or: $value.createdAt),
      autoGeneratedUsername:
          data.get(#autoGeneratedUsername, or: $value.autoGeneratedUsername),
      usernameChangeCounter:
          data.get(#usernameChangeCounter, or: $value.usernameChangeCounter),
      channels: data.get(#channels, or: $value.channels),
      deviceType: data.get(#deviceType, or: $value.deviceType),
      deviceId: data.get(#deviceId, or: $value.deviceId),
      providerId: data.get(#providerId, or: $value.providerId),
      posts: data.get(#posts, or: $value.posts),
      storys: data.get(#storys, or: $value.storys),
      comments: data.get(#comments, or: $value.comments),
      reports: data.get(#reports, or: $value.reports),
      reporteds: data.get(#reporteds, or: $value.reporteds),
      tokens: data.get(#tokens, or: $value.tokens));

  @override
  UserModelCopyWith<$R2, UserModel, $Out2> $chain<$R2, $Out2>(
          Then<$Out2, $R2> t) =>
      _UserModelCopyWithImpl($value, $cast, t);
}
